/**
 * Milestones seed data
 * These are all available milestones that users can unlock
 */
const MILESTONES_DATA = [
  // === FIRST STEPS (Common) ===
  {
    id: 'first_forge',
    title: 'First Forge',
    description: 'Complete your first game in any mode',
    icon: '🔥',
    rarity: 'common',
    category: 'games',
    checkType: 'totalGames',
    threshold: 1,
  },
  {
    id: 'word_smith',
    title: 'Word Smith',
    description: 'Forge 10 words in a single game',
    icon: '📝',
    rarity: 'common',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 10,
  },
  {
    id: 'score_100',
    title: 'Century',
    description: 'Score 100 points in one game',
    icon: '💯',
    rarity: 'common',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 100,
  },
  {
    id: 'gamer_5',
    title: 'Casual Player',
    description: 'Play 5 games',
    icon: '🎮',
    rarity: 'common',
    category: 'games',
    checkType: 'totalGames',
    threshold: 5,
  },
  {
    id: 'points_500',
    title: 'Five Hundred',
    description: 'Score 500 total points',
    icon: '💎',
    rarity: 'common',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 500,
  },

  // === EARLY PROGRESS (Common) ===
  {
    id: 'normal_veteran',
    title: 'Normal Mode Explorer',
    description: 'Complete 3 Normal Mode games',
    icon: '⚔️',
    rarity: 'common',
    category: 'games',
    checkType: 'normalGames',
    threshold: 3,
  },
  {
    id: 'time_trial',
    title: 'Time Trial Rookie',
    description: 'Play your first Time Attack game',
    icon: '⏱️',
    rarity: 'common',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 1,
  },
  {
    id: 'word_expert',
    title: 'Word Expert',
    description: 'Forge 25 words in a single game',
    icon: '🏆',
    rarity: 'common',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 25,
  },
  {
    id: 'gamer_10',
    title: 'Getting Serious',
    description: 'Play 10 games',
    icon: '🎯',
    rarity: 'common',
    category: 'games',
    checkType: 'totalGames',
    threshold: 10,
  },
  {
    id: 'points_1000',
    title: 'Millionaire',
    description: 'Score 1,000 total points',
    icon: '🏅',
    rarity: 'common',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 1000,
  },

  // === INTERMEDIATE (Rare) ===
  {
    id: 'perfect_game',
    title: 'Perfect Game',
    description: 'Bonus for precision gameplay',
    icon: '🌟',
    rarity: 'rare',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 15,
  },
  {
    id: 'forging_master',
    title: 'Forging Master',
    description: 'Complete 10 Normal Mode games',
    icon: '🛡️',
    rarity: 'rare',
    category: 'games',
    checkType: 'normalGames',
    threshold: 10,
  },
  {
    id: 'blitz_rookie',
    title: 'Blitz Rookie',
    description: 'Play 3 Time Attack games',
    icon: '⚡',
    rarity: 'rare',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 3,
  },
  {
    id: 'word_master',
    title: 'Word Master',
    description: 'Forge 50 words in a single game',
    icon: '📚',
    rarity: 'rare',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 50,
  },
  {
    id: 'points_5000',
    title: 'High Scorer',
    description: 'Score 5,000 total points',
    icon: '💰',
    rarity: 'rare',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 5000,
  },
  {
    id: 'gamer_25',
    title: 'Dedicated Forger',
    description: 'Play 25 games',
    icon: '🎖️',
    rarity: 'rare',
    category: 'games',
    checkType: 'totalGames',
    threshold: 25,
  },

  // === ADVANCED (Rare) ===
  {
    id: 'blitz_master',
    title: 'Blitz Master',
    description: 'Play 10 Time Attack games',
    icon: '🏹',
    rarity: 'rare',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 10,
  },
  {
    id: 'normal_veteran_plus',
    title: 'Normal Veteran',
    description: 'Complete 25 Normal Mode games',
    icon: '🗡️',
    rarity: 'rare',
    category: 'games',
    checkType: 'normalGames',
    threshold: 25,
  },
  {
    id: 'speed_demon',
    title: 'Speed Demon',
    description: 'Achieve high efficiency - 20 points per word avg',
    icon: '🚀',
    rarity: 'rare',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 20,
  },
  {
    id: 'word_legend',
    title: 'Word Legend',
    description: 'Forge 100 words in a single game',
    icon: '📖',
    rarity: 'rare',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 100,
  },
  {
    id: 'points_10000',
    title: 'Ten Thousand Club',
    description: 'Score 10,000 total points',
    icon: '👑',
    rarity: 'rare',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 10000,
  },

  // === SURVIVAL MODE (Common/Rare) ===
  {
    id: 'survivor_1',
    title: 'Novice Survivor',
    description: 'Survive 5 rounds in Endless Mode',
    icon: '🔥',
    rarity: 'common',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 5,
  },
  {
    id: 'survivor_5',
    title: 'Skilled Survivor',
    description: 'Survive 15 rounds in Endless Mode',
    icon: '⚔️',
    rarity: 'common',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 15,
  },
  {
    id: 'survivor_15',
    title: 'Seasoned Survivor',
    description: 'Survive 30 rounds in Endless Mode',
    icon: '🛡️',
    rarity: 'rare',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 30,
  },
  {
    id: 'survivor_30',
    title: 'Master Survivor',
    description: 'Survive 50 rounds in Endless Mode',
    icon: '🏆',
    rarity: 'rare',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 50,
  },
  {
    id: 'survivor_50',
    title: 'Elite Survivor',
    description: 'Survive 75 rounds in Endless Mode',
    icon: '👑',
    rarity: 'epic',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 75,
  },
  {
    id: 'survivor_100',
    title: 'Legendary Survivor',
    description: 'Survive 100 rounds in Endless Mode',
    icon: '💪',
    rarity: 'legendary',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 100,
  },

  // === CHAIN MODE (Common/Rare) ===
  {
    id: 'chain_3',
    title: 'Chain Starter',
    description: 'Chain 3 words in Chain Mode',
    icon: '🔗',
    rarity: 'common',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 3,
  },
  {
    id: 'chain_5',
    title: 'Chain Apprentice',
    description: 'Chain 5 words in Chain Mode',
    icon: '⚡',
    rarity: 'common',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 5,
  },
  {
    id: 'chain_10',
    title: 'Chain Expert',
    description: 'Chain 10 words in Chain Mode',
    icon: '🎯',
    rarity: 'rare',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 10,
  },
  {
    id: 'chain_15',
    title: 'Chain Master',
    description: 'Chain 15 words in Chain Mode',
    icon: '🏆',
    rarity: 'rare',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 15,
  },
  {
    id: 'chain_20',
    title: 'Chain Legend',
    description: 'Chain 20 words in Chain Mode',
    icon: '🌟',
    rarity: 'epic',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 20,
  },
  {
    id: 'chain_25',
    title: 'Chain God',
    description: 'Chain 25 words in Chain Mode',
    icon: '👑',
    rarity: 'legendary',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 25,
  },

  // === SURVIVAL MODE - Game Count Tiers ===
  {
    id: 'survival_first',
    title: 'Endless Initiate',
    description: 'Complete your first Endless Mode game',
    icon: '🕯️',
    rarity: 'common',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 1,
  },
  {
    id: 'survival_3_games',
    title: 'Endless Explorer',
    description: 'Complete 3 Endless Mode games',
    icon: '🏕️',
    rarity: 'common',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 3,
  },
  {
    id: 'survival_10_games',
    title: 'Endless Veteran',
    description: 'Complete 10 Endless Mode games',
    icon: '🔥',
    rarity: 'rare',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 10,
  },
  {
    id: 'survival_25_games',
    title: 'Endless Champion',
    description: 'Complete 25 Endless Mode games',
    icon: '🛡️',
    rarity: 'epic',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 25,
  },
  {
    id: 'survival_50_games',
    title: 'Endless Legend',
    description: 'Complete 50 Endless Mode games',
    icon: '👑',
    rarity: 'legendary',
    category: 'survival',
    checkType: 'survivalGames',
    threshold: 50,
  },

  // === CHAIN MODE - Game Count Tiers ===
  {
    id: 'chain_first',
    title: 'Chain Initiate',
    description: 'Complete your first Chain Mode game',
    icon: '🔗',
    rarity: 'common',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 1,
  },
  {
    id: 'chain_3_games',
    title: 'Chain Explorer',
    description: 'Complete 3 Chain Mode games',
    icon: '⛓️',
    rarity: 'common',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 3,
  },
  {
    id: 'chain_10_games',
    title: 'Chain Veteran',
    description: 'Complete 10 Chain Mode games',
    icon: '🔄',
    rarity: 'rare',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 10,
  },
  {
    id: 'chain_25_games',
    title: 'Chain Champion',
    description: 'Complete 25 Chain Mode games',
    icon: '🎯',
    rarity: 'epic',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 25,
  },
  {
    id: 'chain_50_games',
    title: 'Chain Legend',
    description: 'Complete 50 Chain Mode games',
    icon: '🌟',
    rarity: 'legendary',
    category: 'chain',
    checkType: 'chainGames',
    threshold: 50,
  },

  // === CROSS-MODE MILESTONES ===
  {
    id: 'all_modes_played',
    title: 'Mode Explorer',
    description: 'Play at least 1 game in every mode',
    icon: '🌐',
    rarity: 'common',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'mode_dabbler',
    title: 'Mode Dabbler',
    description: 'Play 5 games in each of the 4 modes',
    icon: '🎨',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'mode_specialist',
    title: 'Mode Specialist',
    description: 'Play 20 games in each of the 4 modes',
    icon: '🏆',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'mode_omniscient',
    title: 'Mode Omniscient',
    description: 'Play 50 games in each of the 4 modes',
    icon: '👑',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'survival_only_master',
    title: 'Endless Purist',
    description: 'Complete 50 games in Endless Mode and fewer than 10 in any other mode',
    icon: '🕯️',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'chain_perfectionist',
    title: 'Chain Perfectionist',
    description: 'Complete a Chain Mode game without breaking the chain once',
    icon: '✨',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'survival_high_score',
    title: 'Endless High Roller',
    description: 'Score 500+ points in a single Endless Mode game',
    icon: '💰',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'chain_speed_run',
    title: 'Chain Speedster',
    description: 'Complete 15 chains in under 2 minutes',
    icon: '⚡',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },

  // === EXPERT (Epic) ===
  {
    id: 'gamer_50',
    title: 'Expert Forger',
    description: 'Play 50 games',
    icon: '💪',
    rarity: 'epic',
    category: 'games',
    checkType: 'totalGames',
    threshold: 50,
  },
  {
    id: 'blitz_legend',
    title: 'Blitz Legend',
    description: 'Play 25 Time Attack games',
    icon: '🔥',
    rarity: 'epic',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 25,
  },
  {
    id: 'normal_champion',
    title: 'Normal Champion',
    description: 'Complete 50 Normal Mode games',
    icon: '🏰',
    rarity: 'epic',
    category: 'games',
    checkType: 'normalGames',
    threshold: 50,
  },
  {
    id: 'perfect_efficiency',
    title: 'Forging Perfection',
    description: 'Achieve 25 points per word average',
    icon: '✨',
    rarity: 'epic',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 25,
  },
  {
    id: 'points_25000',
    title: 'Points Baron',
    description: 'Score 25,000 total points',
    icon: '💎',
    rarity: 'epic',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 25000,
  },

  // === MASTER (Epic) ===
  {
    id: 'gamer_100',
    title: 'Master Forger',
    description: 'Play 100 games',
    icon: '🏆',
    rarity: 'epic',
    category: 'games',
    checkType: 'totalGames',
    threshold: 100,
  },
  {
    id: 'blitz_king',
    title: 'Blitz King',
    description: 'Play 50 Time Attack games',
    icon: '⚔️',
    rarity: 'epic',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 50,
  },
  {
    id: 'word_titan',
    title: 'Word Titan',
    description: 'Forge 200+ words in a single game',
    icon: '🎪',
    rarity: 'epic',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 200,
  },
  {
    id: 'points_50000',
    title: 'Points King',
    description: 'Score 50,000 total points',
    icon: '👑',
    rarity: 'epic',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 50000,
  },
  {
    id: 'ultimate_forger',
    title: 'Ultimate Forger',
    description: 'Play 75 games in any mode',
    icon: '🎯',
    rarity: 'epic',
    category: 'games',
    checkType: 'totalGames',
    threshold: 75,
  },

  // === LEGENDARY (Legendary) ===
  {
    id: 'gamer_200',
    title: 'Legendary Forger',
    description: 'Play 200 games',
    icon: '🏅',
    rarity: 'legendary',
    category: 'games',
    checkType: 'totalGames',
    threshold: 200,
  },
  {
    id: 'blitz_god',
    title: 'Time Attack God',
    description: 'Play 100 Time Attack games',
    icon: '🌠',
    rarity: 'legendary',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 100,
  },
  {
    id: 'word_novelist',
    title: 'The Novelist',
    description: 'Forge 300+ words in a single game',
    icon: '📜',
    rarity: 'legendary',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 300,
  },
  {
    id: 'points_100000',
    title: 'God of Points',
    description: 'Score 100,000 total points',
    icon: '💯',
    rarity: 'legendary',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 100000,
  },
  {
    id: 'forging_legend',
    title: 'Forging Legend',
    description: 'Complete 100 games in any mode',
    icon: '🎖️',
    rarity: 'legendary',
    category: 'games',
    checkType: 'totalGames',
    threshold: 100,
  },

  // === SPECIAL (Mixed) ===
  {
    id: 'versatile',
    title: 'Versatile Player',
    description: 'Play at least 5 games in each mode',
    icon: '🎭',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'balanced_warrior',
    title: 'Balanced Warrior',
    description: 'Equal parts Normal and Time Attack (10 each)',
    icon: '⚖️',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'points_perfect',
    title: 'Points Perfectionist',
    description: 'Average 30+ points per word',
    icon: '💫',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_producer',
    title: 'Word Producer',
    description: 'Forge 150 words in a single game',
    icon: '📦',
    rarity: 'epic',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 150,
  },
  {
    id: 'blitz_starter',
    title: 'Blitz Starter',
    description: 'Complete your first 5 games in Time Attack',
    icon: '🎪',
    rarity: 'common',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 5,
  },

  // === GAME COUNT SPECIALS ===
  {
    id: 'gamer_150',
    title: 'Game Master',
    description: 'Play 150 games total',
    icon: '🎪',
    rarity: 'epic',
    category: 'games',
    checkType: 'totalGames',
    threshold: 150,
  },
  {
    id: 'normal_pro',
    title: 'Normal Mode Pro',
    description: 'Complete 35 Normal Mode games',
    icon: '🎲',
    rarity: 'rare',
    category: 'games',
    checkType: 'normalGames',
    threshold: 35,
  },
  {
    id: 'time_pro',
    title: 'Time Attack Pro',
    description: 'Complete 15 Time Attack games',
    icon: '🎪',
    rarity: 'rare',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 15,
  },

  // === ADDITIONAL MILESTONES (to reach 100) ===

  // Words milestones
  {
    id: 'word_scout',
    title: 'Word Scout',
    description: 'Forge 5 words in a single game',
    icon: '🔍',
    rarity: 'common',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 5,
  },
  {
    id: 'word_architect',
    title: 'Word Architect',
    description: 'Forge 75 words in a single game',
    icon: '🏗️',
    rarity: 'rare',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 75,
  },
  {
    id: 'word_sage',
    title: 'Word Sage',
    description: 'Forge 125 words in a single game',
    icon: '📖',
    rarity: 'epic',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 125,
  },
  {
    id: 'word_oracle',
    title: 'Word Oracle',
    description: 'Forge 250 words in a single game',
    icon: '🔮',
    rarity: 'legendary',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 250,
  },
  {
    id: 'word_bard',
    title: 'Word Bard',
    description: 'Forge 400 words in a single game',
    icon: '🎭',
    rarity: 'legendary',
    category: 'words',
    checkType: 'maxWordStreak',
    threshold: 400,
  },

  // Points milestones
  {
    id: 'points_250',
    title: 'Quick Start',
    description: 'Score 250 total points',
    icon: '⚡',
    rarity: 'common',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 250,
  },
  {
    id: 'points_2000',
    title: 'Point Pioneer',
    description: 'Score 2,000 total points',
    icon: '🚩',
    rarity: 'rare',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 2000,
  },
  {
    id: 'points_15000',
    title: 'Point Prophet',
    description: 'Score 15,000 total points',
    icon: '💫',
    rarity: 'epic',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 15000,
  },
  {
    id: 'points_75000',
    title: 'Point Potentate',
    description: 'Score 75,000 total points',
    icon: '🌟',
    rarity: 'legendary',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 75000,
  },
  {
    id: 'points_250000',
    title: 'Point Paragon',
    description: 'Score 250,000 total points',
    icon: '🌌',
    rarity: 'legendary',
    category: 'points',
    checkType: 'totalPoints',
    threshold: 250000,
  },

  // Game count milestones (tiers)
  {
    id: 'gamer_2',
    title: 'Curious Player',
    description: 'Play 2 games',
    icon: '🎲',
    rarity: 'common',
    category: 'games',
    checkType: 'totalGames',
    threshold: 2,
  },
  {
    id: 'gamer_15',
    title: 'Rising Star',
    description: 'Play 15 games',
    icon: '⭐',
    rarity: 'common',
    category: 'games',
    checkType: 'totalGames',
    threshold: 15,
  },
  {
    id: 'gamer_30',
    title: 'Regular Player',
    description: 'Play 30 games',
    icon: '🎮',
    rarity: 'rare',
    category: 'games',
    checkType: 'totalGames',
    threshold: 30,
  },
  {
    id: 'gamer_75',
    title: 'Avid Player',
    description: 'Play 75 games',
    icon: '🎯',
    rarity: 'epic',
    category: 'games',
    checkType: 'totalGames',
    threshold: 75,
  },
  {
    id: 'gamer_125',
    title: 'Seasoned Veteran',
    description: 'Play 125 games',
    icon: '🏆',
    rarity: 'epic',
    category: 'games',
    checkType: 'totalGames',
    threshold: 125,
  },

  // Normal mode milestones
  {
    id: 'normal_rookie',
    title: 'Normal Rookie',
    description: 'Complete 1 Normal Mode game',
    icon: '🌱',
    rarity: 'common',
    category: 'games',
    checkType: 'normalGames',
    threshold: 1,
  },
  {
    id: 'normal_apprentice',
    title: 'Normal Apprentice',
    description: 'Complete 5 Normal Mode games',
    icon: '📚',
    rarity: 'common',
    category: 'games',
    checkType: 'normalGames',
    threshold: 5,
  },
  {
    id: 'normal_journeyman',
    title: 'Normal Journeyman',
    description: 'Complete 15 Normal Mode games',
    icon: '⚔️',
    rarity: 'rare',
    category: 'games',
    checkType: 'normalGames',
    threshold: 15,
  },
  {
    id: 'normal_expert',
    title: 'Normal Expert',
    description: 'Complete 40 Normal Mode games',
    icon: '🎯',
    rarity: 'epic',
    category: 'games',
    checkType: 'normalGames',
    threshold: 40,
  },
  {
    id: 'normal_master',
    title: 'Normal Master',
    description: 'Complete 75 Normal Mode games',
    icon: '👑',
    rarity: 'legendary',
    category: 'games',
    checkType: 'normalGames',
    threshold: 75,
  },

  // Time Attack milestones
  {
    id: 'time_apprentice',
    title: 'Time Apprentice',
    description: 'Complete 2 Time Attack games',
    icon: '⏳',
    rarity: 'common',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 2,
  },
  {
    id: 'time_veteran',
    title: 'Time Veteran',
    description: 'Complete 8 Time Attack games',
    icon: '🕐',
    rarity: 'rare',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 8,
  },
  {
    id: 'time_expeditor',
    title: 'Time Expeditor',
    description: 'Complete 20 Time Attack games',
    icon: '⚡',
    rarity: 'epic',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 20,
  },
  {
    id: 'time_savant',
    title: 'Time Savant',
    description: 'Complete 45 Time Attack games',
    icon: '⏰',
    rarity: 'legendary',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 45,
  },
  {
    id: 'time_chronomancer',
    title: 'Time Chronomancer',
    description: 'Complete 100 Time Attack games',
    icon: '⌛',
    rarity: 'legendary',
    category: 'time_attack',
    checkType: 'timedGames',
    threshold: 100,
  },

  // Efficiency milestones (avg points per word)
  {
    id: 'efficiency_10',
    title: 'Efficient Starter',
    description: 'Average 10 points per word',
    icon: '📊',
    rarity: 'common',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 10,
  },
  {
    id: 'efficiency_12',
    title: 'Efficient Player',
    description: 'Average 12 points per word',
    icon: '📈',
    rarity: 'common',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 12,
  },
  {
    id: 'efficiency_18',
    title: 'Efficient Pro',
    description: 'Average 18 points per word',
    icon: '📉',
    rarity: 'rare',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 18,
  },
  {
    id: 'efficiency_22',
    title: 'Efficiency Expert',
    description: 'Average 22 points per word',
    icon: '🎯',
    rarity: 'epic',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 22,
  },
  {
    id: 'efficiency_28',
    title: 'Efficiency God',
    description: 'Average 28 points per word',
    icon: '🌟',
    rarity: 'legendary',
    category: 'special',
    checkType: 'avgPointsPerWord',
    threshold: 28,
  },

  // Combo/Special milestones
  {
    id: 'dual_master',
    title: 'Dual Master',
    description: '25 games in each mode',
    icon: '🔱',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'triple_play',
    title: 'Triple Play',
    description: '50 games in each mode',
    icon: '🎲',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'consistency_king',
    title: 'Consistency King',
    description: '200+ points in 50% of games',
    icon: '👑',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'streak_warrior',
    title: 'Streak Warrior',
    description: 'Complete 10 games in 7 days',
    icon: '🔥',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'perfect_month',
    title: 'Perfect Month',
    description: 'Play every day for 30 days',
    icon: '📅',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },

  // Daily/Weekly score milestones
  {
    id: 'daily_100',
    title: 'Daily Centurion',
    description: 'Score 100 points in a day',
    icon: '☀️',
    rarity: 'common',
    category: 'points',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'daily_500',
    title: 'Daily Dynamo',
    description: 'Score 500 points in a day',
    icon: '⚡',
    rarity: 'rare',
    category: 'points',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'weekly_1000',
    title: 'Weekly Warrior',
    description: 'Score 1,000 points in a week',
    icon: '🗓️',
    rarity: 'rare',
    category: 'points',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'weekly_5000',
    title: 'Weekly Whiz',
    description: 'Score 5,000 points in a week',
    icon: '🏆',
    rarity: 'epic',
    category: 'points',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'monthly_15000',
    title: 'Monthly Master',
    description: 'Score 15,000 points in a month',
    icon: '📆',
    rarity: 'epic',
    category: 'points',
    checkType: 'special',
    threshold: null,
  },

  // Word variety milestones
  {
    id: 'word_collect_50',
    title: 'Word Collector',
    description: 'Find 50 unique words',
    icon: '📚',
    rarity: 'common',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_collect_200',
    title: 'Word Curator',
    description: 'Find 200 unique words',
    icon: '📖',
    rarity: 'rare',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_collect_500',
    title: 'Word Scholar',
    description: 'Find 500 unique words',
    icon: '🎓',
    rarity: 'epic',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_collect_1000',
    title: 'Word Lexicon',
    description: 'Find 1,000 unique words',
    icon: '📜',
    rarity: 'legendary',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_encyclopedia',
    title: 'Word Encyclopedia',
    description: 'Find 2,500 unique words',
    icon: '📕',
    rarity: 'legendary',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },

  // Achievement milestones
  {
    id: 'first_week',
    title: 'First Week',
    description: 'Play for 7 consecutive days',
    icon: '📅',
    rarity: 'common',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'first_month',
    title: 'First Month',
    description: 'Play for 30 consecutive days',
    icon: '🗓️',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'early_bird',
    title: 'Early Bird',
    description: 'Play before 6 AM 10 times',
    icon: '🐦',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'night_owl',
    title: 'Night Owl',
    description: 'Play after 10 PM 10 times',
    icon: '🦉',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'weekend_warrior',
    title: 'Weekend Warrior',
    description: 'Play 10 games on weekends',
    icon: '🎮',
    rarity: 'common',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },

  // Challenge milestones
  {
    id: 'speed_demon_100',
    title: 'Demon Speed',
    description: 'Score 100 points in under 30 seconds',
    icon: '⚡',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'no_miss_gamer',
    title: 'Perfect Precision',
    description: 'Complete a game with 100% valid words',
    icon: '💎',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'max_rush',
    title: 'Word Rush',
    description: 'Submit 10 words in under 60 seconds',
    icon: '🏃',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'marathon_mode',
    title: 'Marathon Mode',
    description: 'Play 20 games in a single day',
    icon: '🏃‍♂️',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'jackpot_winner',
    title: 'Jackpot Winner',
    description: 'Score 500+ points in a single game',
    icon: '🎰',
    rarity: 'epic',
    category: 'points',
    checkType: 'special',
    threshold: null,
  },

  // Bonus milestones for variety
  {
    id: 'word_explorer_3',
    title: 'Word Explorer',
    description: 'Use 3-letter words at least 50 times',
    icon: '🔍',
    rarity: 'common',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_explorer_4',
    title: 'Word Journeyer',
    description: 'Use 4-letter words at least 50 times',
    icon: '🗺️',
    rarity: 'common',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_explorer_5',
    title: 'Word Voyager',
    description: 'Use 5-letter words at least 50 times',
    icon: '🧭',
    rarity: 'rare',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_artisan',
    title: 'Word Artisan',
    description: 'Use 6-letter words at least 30 times',
    icon: '🎨',
    rarity: 'rare',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'word_masterclass',
    title: 'Word Masterclass',
    description: 'Use 7+ letter words at least 20 times',
    icon: '🎓',
    rarity: 'epic',
    category: 'words',
    checkType: 'special',
    threshold: null,
  },

  // Social and community milestones
  {
    id: 'social_butterfly',
    title: 'Social Butterfly',
    description: 'Share scores 10 times',
    icon: '🦋',
    rarity: 'common',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'community_sharer',
    title: 'Community Sharer',
    description: 'Share scores 50 times',
    icon: '🌐',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'influencer',
    title: 'Influencer',
    description: 'Share scores 100 times',
    icon: '👥',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'viral_star',
    title: 'Viral Star',
    description: 'Share scores 250 times',
    icon: '🌟',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'content_king',
    title: 'Content Creator',
    description: 'Create and share content',
    icon: '📹',
    rarity: 'epic',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },

  // Seasonal and event milestones
  {
    id: 'spring_champion',
    title: 'Spring Champion',
    description: 'High scorer during spring season',
    icon: '🌸',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'summer_surfer',
    title: 'Summer Surfer',
    description: 'High scorer during summer season',
    icon: '☀️',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'autumn_archer',
    title: 'Autumn Archer',
    description: 'High scorer during autumn season',
    icon: '🍂',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'winter_warrior',
    title: 'Winter Warrior',
    description: 'High scorer during winter season',
    icon: '❄️',
    rarity: 'rare',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'season_champion',
    title: 'Season Champion',
    description: 'High scorer in consecutive seasons',
    icon: '🏆',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },

  // Ultimate milestones
  {
    id: 'letterforge_master',
    title: 'LetterForge Master',
    description: 'Achieve all common milestones',
    icon: '🏆',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'letterforge_legend',
    title: 'LetterForge Legend',
    description: 'Achieve all rare milestones',
    icon: '👑',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
  {
    id: 'letterforge_god',
    title: 'LetterForge God',
    description: 'Achieve all epic milestones',
    icon: '⚡',
    rarity: 'legendary',
    category: 'special',
    checkType: 'special',
    threshold: null,
  },
];

module.exports = { MILESTONES_DATA };
